menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags

excerpt:
  enable: true
  length: 150

toc:
  enable: true
  class: toc
  list_number: false
  min_depth: 1
  max_depth: 4
